In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

## Define  the vocubulary Size

In [6]:
voc_size = 10000

## One Hot Representation

In [8]:
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[6988, 4970, 1966, 8067],
 [6988, 4970, 1966, 1032],
 [6988, 1093, 1966, 4477],
 [2291, 3166, 1634, 5327, 3987],
 [2291, 3166, 1634, 5327, 9327],
 [2365, 6988, 4392, 1966, 8553],
 [3801, 8555, 8694, 5327]]

## Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length) 
print(embedded_docs)

[[   0    0    0    0 6988 4970 1966 8067]
 [   0    0    0    0 6988 4970 1966 1032]
 [   0    0    0    0 6988 1093 1966 4477]
 [   0    0    0 2291 3166 1634 5327 3987]
 [   0    0    0 2291 3166 1634 5327 9327]
 [   0    0    0 2365 6988 4392 1966 8553]
 [   0    0    0    0 3801 8555 8694 5327]]


## Feature Representation

In [13]:
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 126ms/step


array([[[ 0.04888551, -0.02637707,  0.02708841,  0.03318037,
         -0.00105094, -0.02917389, -0.01120576, -0.04851923,
         -0.00147323,  0.02310618],
        [ 0.04888551, -0.02637707,  0.02708841,  0.03318037,
         -0.00105094, -0.02917389, -0.01120576, -0.04851923,
         -0.00147323,  0.02310618],
        [ 0.04888551, -0.02637707,  0.02708841,  0.03318037,
         -0.00105094, -0.02917389, -0.01120576, -0.04851923,
         -0.00147323,  0.02310618],
        [ 0.04888551, -0.02637707,  0.02708841,  0.03318037,
         -0.00105094, -0.02917389, -0.01120576, -0.04851923,
         -0.00147323,  0.02310618],
        [ 0.02283517, -0.01029612,  0.01915015,  0.03055134,
         -0.02530191,  0.01617182,  0.01779082, -0.00337905,
         -0.00941082, -0.00814991],
        [ 0.03230735,  0.00966555, -0.03455421,  0.04287872,
          0.00254955, -0.03111886,  0.00301398,  0.02327467,
         -0.04759751,  0.04288954],
        [ 0.02543527,  0.03567067, -0.04612077, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 6988, 4970, 1966, 8067])